# ---- Base Node ----
FROM node:alpine as base
WORKDIR /app
COPY package.json yarn.lock ./

# ---- Dependencies ----
FROM base AS dependencies
RUN yarn --production=false

# ---- Copy Files/Run ----
FROM dependencies AS development
WORKDIR /app
COPY . .
EXPOSE 8080
CMD ["yarn", "start:dev"]